version: "3"
services:
  recsys:
    image: bigdatarepublic/data-science-recommender-systems:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8889 --no-browser --allow-root"
    ports:
    - 8889:8889
    volumes:
    - ./notebooks:/opt/notebooks
    - ./src:/opt/src